[build]
  publish = "dist"
  command = "npm run build"

# Specifically handle the auth v1 callback route
[[redirects]]
  from = "/auth/v1/callback"
  to = "/index.html"
  status = 200
  force = true

# Specifically handle the auth callback route
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper content types for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Proper content types for CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Proper content types for SVG files
[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Proper content types for asset files
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
